name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "7 3 21 * *"

jobs:
  html_documentation_link_checks:
    timeout-minutes: 5
    if: github.repository_owner == 'dzimmer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python packages
        run: pip install --user futures
      - name: Check links
        timeout-minutes: 3
        run: python ./.CI/check_html.py checkLinks ./
  spelling_checks:
    timeout-minutes: 5
    if: github.repository_owner == 'dzimmer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python packages
        run:  pip install --user codespell
      - name: Check for spelling errors
        run: |
          printf "[codespell]\nenable-colors=\n" >> .codespellrc
          codespell -L nin ./PlanarMechanics/Utilities/Blocks/SquaretimesSign.mo
          codespell --skip ./.CI,./.github,./.git,*.png -L nin
  clean_workflow_runs:
    timeout-minutes: 5
    if: github.repository_owner == 'dzimmer'
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1
        with:
          run_conclusions: skipped,success
          save_period: 60
          save_min_runs_number: 6
          dry: false
